# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: false

    strategy:
      matrix:
        node-version: [18.13.0]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        name: Install
      - run: npm run test-single-headless
        name: Test
      - run: npm run test:coveralls
        name: Publish Test Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls }}
      - run: npm run lint
        name: Lint
      - run: npm run format:check
        name: Format
      - run: npm run build
        name: Build
      - name: Write Configuration
        uses: microsoft/variable-substitution@v1
        with:
          files: 'dist/ng-radio/assets/config/app.config.json'
        env:
          appInsightsInstrumentationKey: ${{ secrets.appinsights_instrumentation_key }}
          authConfig.userManager.client_id: OUO72IMzQPFkpXz5IkVMAnaDM0iKtK3t
          authConfig.userManager.authority: https://browninglogic.auth0.com/
          authConfig.userManager.redirect_uri: https://radio.browninglogic.com/login-callback.html
          authConfig.userManager.post_logout_redirect_uri: https://radio.browninglogic.com
          authConfig.userManager.silent_redirect_uri: https://radio.browninglogic.com/silent-refresh.html
          authConfig.userManager.extraQueryParams.audience: browninglogic-radio
          authConfig.logoutUrl: https://browninglogic.auth0.com/v2/logout?returnTo=http%3A%2F%2Fradio.browninglogic.com
          imageProxyUrl: https://fast-everglades-74198.herokuapp.com
          favoriteStationsApiUrl: https://favorite-stations-api.azurewebsites.net
          radioProxyUrl: https://radio-proxy-2-91a50a6e0820.herokuapp.com
      - name: FTP Deploy
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.0.1
        with:
          ftp_host: ${{ secrets.ftp_host }}
          ftp_username: ${{ secrets.ftp_username }}
          ftp_password: ${{ secrets.ftp_password }}
          local_source_dir: 'dist/ng-radio'
          dist_target_dir: '/'
          disable_ssl_certificate_verification: true
          delete: true
