# .github/workflows/build-template.yml
name: Build Template

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
env:
  artifactName: buildArtifact

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
        name: Install
      - run: npm run test-single-headless
        name: Test
      - run: npm run lint
        name: Lint
      - run: npm run build
        name: Build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifactName }}
          path: ./
