# .github/workflows/build-and-deploy.yml
name: Build and Deploy

on:
  push:
    branches: [master]
env:
  artifactName: buildArtifact

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      node-version: '18.13.0'
    concurrency:
      group: build-and-deploy
      cancel-in-progress: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: build-and-deploy
      cancel-in-progress: true
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifactName }}
          path: ./buildArtifact
      - name: FTP Deploy
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.0.1
        with:
          ftp_host: ${{ secrets.ftp_host }}
          ftp_username: ${{ secrets.ftp_username }}
          ftp_password: ${{ secrets.ftp_password }}
          local_source_dir: './buildArtifact/dist/ng-radio'
          dist_target_dir: '/'
          disable_ssl_certificate_verification: true
          delete: true
