# .github/workflows/build-and-deploy.yml
name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      node-version: '18.13.0'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: build-and-deploy
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
      - run: npm run test:coveralls
        name: Publish Test Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls }}
      - name: Write Configuration
        uses: microsoft/variable-substitution@v1
        with:
          files: 'dist/ng-radio/assets/config/app.config.json'
        env:
          appInsightsInstrumentationKey: ${{ secrets.appinsights_instrumentation_key }}
          authConfig.userManager.client_id: OUO72IMzQPFkpXz5IkVMAnaDM0iKtK3t
          authConfig.userManager.authority: https://browninglogic.auth0.com/
          authConfig.userManager.redirect_uri: https://radio.browninglogic.com/login-callback.html
          authConfig.userManager.post_logout_redirect_uri: https://radio.browninglogic.com
          authConfig.userManager.silent_redirect_uri: https://radio.browninglogic.com/silent-refresh.html
          authConfig.userManager.extraQueryParams.audience: browninglogic-radio
          authConfig.logoutUrl: https://browninglogic.auth0.com/v2/logout?returnTo=http%3A%2F%2Fradio.browninglogic.com
          imageProxyUrl: https://fast-everglades-74198.herokuapp.com
          favoriteStationsApiUrl: https://favorite-stations-api.azurewebsites.net
          radioProxyUrl: https://radio-proxy-2-91a50a6e0820.herokuapp.com
      - name: FTP Deploy
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.0.1
        with:
          ftp_host: ${{ secrets.ftp_host }}
          ftp_username: ${{ secrets.ftp_username }}
          ftp_password: ${{ secrets.ftp_password }}
          local_source_dir: 'dist/ng-radio'
          dist_target_dir: '/'
          disable_ssl_certificate_verification: true
          delete: true
