# .github/workflows/build-template.yml
name: Build Template

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      publish-test-coverage:
        required: false
        type: boolean
        default: false
env:
  artifactName: buildArtifact

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
        name: Install
      - run: npm run test-single-headless
        name: Test
      - run: npm run lint
        name: Lint
      - run: npm run build
        name: Build
      - name: Write Configuration
        uses: microsoft/variable-substitution@v1
        with:
          files: 'dist/ng-radio/assets/config/app.config.json'
        env:
          appInsightsInstrumentationKey: ${{ secrets.appinsights_instrumentation_key }}
          authConfig.userManager.client_id: OUO72IMzQPFkpXz5IkVMAnaDM0iKtK3t
          authConfig.userManager.authority: https://browninglogic.auth0.com/
          authConfig.userManager.redirect_uri: https://radio.browninglogic.com/login-callback.html
          authConfig.userManager.post_logout_redirect_uri: https://radio.browninglogic.com
          authConfig.userManager.silent_redirect_uri: https://radio.browninglogic.com/silent-refresh.html
          authConfig.userManager.extraQueryParams.audience: browninglogic-radio
          authConfig.logoutUrl: https://browninglogic.auth0.com/v2/logout?returnTo=http%3A%2F%2Fradio.browninglogic.com
          imageProxyUrl: https://fast-everglades-74198.herokuapp.com
          favoriteStationsApiUrl: https://favorite-stations-api.azurewebsites.net
          radioProxyUrl: https://radio-proxy-2-91a50a6e0820.herokuapp.com
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifactName }}
          path: ./
  publish-test-coverage:
    runs-on: ubuntu-latest
    needs: build
    if: inputs.publish-test-coverage == true
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifactName }}
          path: ./buildArtifact
      - run: npm run test:coveralls
        name: Publish Test Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls }}
