# .github/workflows/build.yml
name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
        name: Install
      - run: npm run test-single-headless
        name: Test
      - run: npm run lint
        name: Lint
      - run: npm run build
        name: Build
